### ISSUE TITLE
Is there a reason why you specify using FTP to transfer to PC and back?

### ISSUE THREAD

**Issue by gensosuikoden** [TheRadziu/NoNpDRM-modding#1]
USB seems quicker to me and doesn't result in certain files failing to transfer.

Many thanks for your work here and on forums.

**Comment by TheRadziu** [comment]
I saw reports of people saying decryption works only through FTP and since I dont use usb at all (just because I prefer using microsd via usb adapter) I never confirmed it or busted it. 

If you test decryption via USB, please do report back.

**Comment by gensosuikoden** [comment]
Hi, have now tested and you were right, my bad. The FTP method ensures that files transferred immediately after decrypting via Vita shell are decrypted. 

The other option would be to decrypt/unpack, edit and repack via PSVimgtools.

Many thanks again.
