### ISSUE TITLE
Undub version of NoNPDRM is not working on 3.65

### ISSUE THREAD

**Issue by bloodfalco** [TheRadziu/NoNpDRM-modding#2]
Hi, TheRadziu. The undub version of FFX, FFX-2 and Persona 4 Golden of yours is unable to be started in 3.65 Enso

It only said file is corrupted.

Hope you can remedy the issue soon.

**Comment by TheRadziu** [comment]
Hello, 
Yes. This happens because 3.61 onwards fixed /patch/ method (basically you cant have non-pfs files there anymore). As soon as I update my own console to 3.65 I'll rewrite whole tutorial with a method that does work on 3.65/3.60  ;)

**Comment by NumberXer0** [comment]
I second this. I'm trying to mod Freedom Wars and it gives the corrupted error.

**Comment by TheRadziu** [comment]
Updated tutorial with new RePatch method and added **Obtaining decrypted game assets from NoNpDRM rips THROUGH VITASHELL [decryption on console].**

Will update rest of the points later today (such as decryption on PC, without using vita at all or eboot modding)
