### ISSUE TITLE
I Can´t aplly mods to official cartridges

### ISSUE THREAD

**Issue by Darkshadow3582** [TheRadziu/NoNpDRM-modding#3]
I tried to place the decrypted and already patched files in the following directories
The game has modified files in both app and patch files

ux0/rePatch/(ID game)/place files here [Nothing]
ux0/rePatch/(ID game)/app/place files here [Nothing]
ux0/rePatch/(ID game)/patch/place files here [Nothing]

Any idea why they do not work correctly?

**Comment by IcySon55** [comment]
I get the feeling that the repatch plugin isn't being loaded. I've only tested with cartridge games and never had an issue.

**Comment by TheRadziu** [comment]
1. do you have repatch plugin installed properly? 
2. your 2nd and 3rd attempt are certainly wrong, first one seems correct. 

Can you give me gameid of this game and what kind of mod / link it you're trying to use?

**Comment by Darkshadow3582** [comment]
Yes, I have the last versión of the plugins

The game id is PCSB00822 (Senran kagura estival versus)

The mod is the uncensored mod v2

**Comment by amadeusnorn** [comment]
i do not know about this mod but either the patch doesnt ONLY contain decrypted files or somehow you configure the plugin wrong

**Comment by TheRadziu** [comment]
```
ux0:/rePatch/PCSB00822/tpk/Chunk00.tpk
ux0:/rePatch/PCSB00822/tpk/Chunk01.tpk
ux0:/rePatch/PCSB00822/tpk/Chunk02.tpk
ux0:/rePatch/PCSB00822/tpk/Chunk22.tpk
ux0:/rePatch/PCSB00822/tpk/Chunk24.tpk
ux0:/rePatch/PCSB00822/tpk/Chunk26.tpk
ux0:/rePatch/PCSB00822/tpk/Chunk27.tpk
ux0:/rePatch/PCSB00822/tpk/Chunk28.tpk
ux0:/rePatch/PCSB00822/tpk/Chunk33.tpk
```

So you placed modded files like that and it is not working for you? If your answer is yes then probably you didn't install repatch plugin properly

**Comment by Darkshadow3582** [comment]
It's just the only directory that I did not try and it seems that now it works
Thanks forma all

So for physical games it would be to create the directory as if it were created by maidump, right?

**Comment by TheRadziu** [comment]
> So for physical games it would be to create the directory as if it were created by maidump, right?

You basically recreate full original structure, that applies to all "types" of games, including cart games, digital games and so on. The structure is always the same no matter if files are encrypted or decrypted. 

I'll add a note about that (+ some examples probably?) on the wiki in few hours.
