### ISSUE TITLE
Is it possible to have a 1:1 decrypted image of an NPDRM eboot.bin?

### ISSUE THREAD

**Issue by mchubby** [TheRadziu/NoNpDRM-modding#4]
Even after decrypting the NPDRM assets (F00D), the eboot.bin is not moddable as-is.

The SELF (SCE header) file format is documented at:
https://vitadevwiki.com/vita/SELF_File_Format
It says 
> ELF sections might be encrypted using AES CTR and signed using ECDSA + HMAC-SHA1. 

There is prior art for decrypting ELF sections https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Crypto/unself.cpp#L740, do you think this can be somehow adapted to produce a valid, decrypted SELF?

AFAICT Maidump 3.65 is dumping the executable from RAM (+ various fixups) and doesn't help in this use case.

**Comment by TheRadziu** [comment]
You're absolutely right about everything, you've done very good research!

Right now we don't have proper tools for SELF/ELF decryption on vita(although we do have SELF < - > ELF tools), but true eboot decryption can be achieved without f00d hack, it is not impossible. Give it more time, maybe few weeks, maybe few months, maybe proper decryption tool will emerge :) 

And yes, Maidump do dump decrypted eboot from console's random access memory, then glues it together and add it's own code for mai module, DLC and plugin's support. End result is very... messy which causes all kinds of issues. Sadly, those eboots are only way to mod eboots right now.

I will keep this issue open until something new is released (data/research or tool itself)

**Comment by dots-tb** [comment]
yes

**Comment by TheRadziu** [comment]
https://github.com/CelesteBlue-dev/PSVita-RE-tools/tree/master/FAGDec
